language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"

install:
  - go get -t -v ./...

before_script:
  - go generate ./...
  - if [[ -n $(git status -s) ]]; then echo "Unclean working tree"; git diff; exit 1; fi
